before_install:
  - gem update --system
  - gem install bundler
language: ruby
matrix:
  allow_failures:
    - rvm: jruby-9000
    - rvm: ruby-head
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - jruby-9000
  - ruby-head
sudo: false
